# Generated by Django 3.2.9 on 2022-03-20 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20220319_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attach_file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
